#!/usr/bin/env bash
# setup.sh — Carnicería Artesanal deployment script
# Supports Ubuntu/Debian (apt) and RHEL/Fedora (dnf/yum)
# Run as root or with sudo.
set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
REPO_URL="https://github.com/manedevo/carniceria-template.git"
INSTALL_DIR="/opt/carniceria-template"
ENV_FILE="${INSTALL_DIR}/.env"
COMPOSE_FILE="${INSTALL_DIR}/docker-compose.yml"

# ── Helpers ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'

info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }
require() { command -v "$1" &>/dev/null || error "Required command not found: $1"; }

# ── Package manager detection ─────────────────────────────────────────────────
detect_pkg_manager() {
  if command -v apt-get &>/dev/null; then PKG_MANAGER="apt"
  elif command -v dnf     &>/dev/null; then PKG_MANAGER="dnf"
  elif command -v yum     &>/dev/null; then PKG_MANAGER="yum"
  else error "No supported package manager found (apt / dnf / yum)"; fi
  info "Package manager: ${PKG_MANAGER}"
}

pkg_install() {
  case "${PKG_MANAGER}" in
    apt) apt-get install -y "$@" ;;
    dnf) dnf install -y "$@"     ;;
    yum) yum install -y "$@"     ;;
  esac
}

# ── Docker installation ───────────────────────────────────────────────────────
install_docker() {
  if command -v docker &>/dev/null; then
    info "Docker already installed: $(docker --version)"; return
  fi

  info "Installing Docker Engine…"
  case "${PKG_MANAGER}" in
    apt)
      pkg_install ca-certificates curl gnupg lsb-release
      install -m 0755 -d /etc/apt/keyrings
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
        | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      chmod a+r /etc/apt/keyrings/docker.gpg
      echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
        https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
        > /etc/apt/sources.list.d/docker.list
      apt-get update -q
      pkg_install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      ;;
    dnf|yum)
      pkg_install yum-utils
      yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      pkg_install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      systemctl enable --now docker
      ;;
  esac
}

# ── Repo sync ─────────────────────────────────────────────────────────────────
sync_repo() {
  if [[ -d "${INSTALL_DIR}/.git" ]]; then
    info "Repository found. Syncing…"
    cd "${INSTALL_DIR}"
    git stash --include-untracked || true
    git fetch origin
    git reset --hard origin/main
    git stash pop 2>/dev/null || true

  elif [[ -d "${INSTALL_DIR}" ]] && [[ -n "$(ls -A "${INSTALL_DIR}" 2>/dev/null)" ]]; then
    error "${INSTALL_DIR} exists and is not a git repository. Remove it manually and re-run."

  else
    info "Cloning repository into ${INSTALL_DIR}…"
    git clone "${REPO_URL}" "${INSTALL_DIR}"
  fi
}

# ── .env generation ───────────────────────────────────────────────────────────
generate_env() {
  if [[ -f "${ENV_FILE}" ]]; then
    warn ".env already exists — skipping generation. Edit it manually if needed."; return
  fi

  info "Generating .env…"
  local db_pass; db_pass=$(openssl rand -hex 24)
  cat > "${ENV_FILE}" <<EOF
# Auto-generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
DB_HOST=db
DB_PORT=3306
DB_USER=carniceria
DB_PASSWORD=${db_pass}
DB_NAME=carniceria_db
PORT=3000
NODE_ENV=production
EOF
  chmod 600 "${ENV_FILE}"
  info ".env written (DB password auto-generated)."
}

# ── Main ──────────────────────────────────────────────────────────────────────
main() {
  [[ "$(id -u)" -eq 0 ]] || error "Run this script as root or with sudo."

  detect_pkg_manager

  info "Updating package lists…"
  case "${PKG_MANAGER}" in
    apt) apt-get update -q              ;;
    dnf) dnf check-update -q || true    ;;
    yum) yum check-update -q || true    ;;
  esac

  info "Installing base dependencies…"
  case "${PKG_MANAGER}" in
    apt) pkg_install git curl openssl ;;
    *)   pkg_install git curl openssl ;;
  esac

  install_docker

  # Add current (non-root) user to docker group if running via sudo
  if [[ -n "${SUDO_USER:-}" ]] && ! groups "${SUDO_USER}" | grep -q docker; then
    usermod -aG docker "${SUDO_USER}"
    warn "User '${SUDO_USER}' added to docker group. Log out and back in (or run: newgrp docker)."
  fi

  sync_repo
  generate_env

  info "Starting services with Docker Compose…"
  cd "${INSTALL_DIR}"
  docker compose -f "${COMPOSE_FILE}" pull --quiet
  docker compose -f "${COMPOSE_FILE}" up -d --build

  info "Waiting for health checks…"
  local retries=30
  while [[ $retries -gt 0 ]]; do
    status=$(docker compose -f "${COMPOSE_FILE}" ps --format json 2>/dev/null \
      | grep -o '"Health":"[^"]*"' | grep -v '"Health":""' | head -1 || echo "")
    [[ "${status}" == *"healthy"* ]] && break
    sleep 3; ((retries--))
  done

  echo ""
  echo -e "${GREEN}══════════════════════════════════════════════${NC}"
  echo -e "${GREEN}  Carnicería Artesanal — deployment complete!  ${NC}"
  echo -e "${GREEN}══════════════════════════════════════════════${NC}"
  echo ""
  echo -e "  App:  http://$(hostname -I | awk '{print $1}'):3000"
  echo -e "  Logs: docker compose -C ${INSTALL_DIR} logs -f"
  echo ""
}

main "$@"
