#!/usr/bin/env bash
set -euo pipefail

echo ""
echo "=== Carniceria Artesanal — Smart Installer ==="
echo ""

# ── Colores ───────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }

#############################################################
##### 1. Detectar dónde está el script
#############################################################

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
info "Script location: $SCRIPT_DIR"


#############################################################
##### 2. Check if we are inside the project directory
#############################################################

is_project() {
    [[ -d "$1/backend" ]] && \
    [[ -f "$1/docker-compose.yml" ]] && \
    [[ -d "$1/public" ]]
}


#############################################################
##### 3. Use local project or clone into /opt/carniceria-template
#############################################################

if is_project "$SCRIPT_DIR"; then
    PROJECT_ROOT="$SCRIPT_DIR"
    info "Project found in current directory."
else
    warn "No project found here."

    INSTALL_DIR="/opt/carniceria-template"

    if [[ ! -d "$INSTALL_DIR" ]]; then
        info "Cloning project into $INSTALL_DIR..."
        sudo git clone https://github.com/manedevo/carniceria-template "$INSTALL_DIR"
    else
        info "Project already exists at $INSTALL_DIR — updating..."
        sudo git -C "$INSTALL_DIR" stash --include-untracked || true
        sudo git -C "$INSTALL_DIR" fetch origin
        sudo git -C "$INSTALL_DIR" reset --hard origin/master
        sudo git -C "$INSTALL_DIR" stash pop 2>/dev/null || true
    fi

    PROJECT_ROOT="$INSTALL_DIR"
fi

info "Project root: $PROJECT_ROOT"


#############################################################
##### 4. Validate project structure
#############################################################

if ! is_project "$PROJECT_ROOT"; then
    error "Project structure is incomplete. Check the folder."
fi


#############################################################
##### 5. Generate .env if it does not exist
#############################################################

ENV_FILE="$PROJECT_ROOT/.env"

if [[ ! -f "$ENV_FILE" ]]; then
    info "Generating .env..."
    db_pass=$(openssl rand -hex 24)
    db_root_pass=$(openssl rand -hex 24)
    cat > "$ENV_FILE" <<EOF
# Auto-generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
DB_HOST=db
DB_PORT=3306
DB_USER=carniceria
DB_PASSWORD=${db_pass}
DB_ROOT_PASSWORD=${db_root_pass}
DB_NAME=carniceria_db
PORT=3000
NODE_ENV=production
EOF
    chmod 600 "$ENV_FILE"
    info ".env created (passwords auto-generated)."
else
    warn ".env already exists — skipping generation. Edit it manually if needed."
fi


#############################################################
##### 6. Patch Dockerfile if it uses npm ci
#############################################################

DOCKERFILE="$PROJECT_ROOT/backend/Dockerfile"

if grep -q "npm ci" "$DOCKERFILE"; then
    info "Patching Dockerfile (npm ci → npm install --omit=dev)..."
    sed -i 's/npm ci --only=production/npm install --omit=dev/' "$DOCKERFILE"
fi


#############################################################
##### 7. Detect distro package manager
#############################################################

if command -v apt-get >/dev/null; then
    PM=apt
elif command -v dnf >/dev/null; then
    PM=dnf
elif command -v yum >/dev/null; then
    PM=yum
elif command -v pacman >/dev/null; then
    PM=pacman
elif command -v zypper >/dev/null; then
    PM=zypper
else
    PM=unknown
fi

info "Package manager detected: $PM"


#############################################################
##### 8. Install base dependencies
#############################################################

info "Updating package lists and installing base dependencies..."
case "$PM" in
    apt)    sudo apt-get update -q && sudo apt-get install -y git curl openssl ;;
    dnf)    sudo dnf check-update -q || true && sudo dnf install -y git curl openssl ;;
    yum)    sudo yum check-update -q || true && sudo yum install -y git curl openssl ;;
    pacman) sudo pacman -Sy --noconfirm git curl openssl ;;
    zypper) sudo zypper install -y git curl openssl ;;
    *)      warn "Could not install base dependencies automatically." ;;
esac


#############################################################
##### 9. Install Docker if not present
#############################################################

if ! command -v docker >/dev/null; then
    info "Docker not found. Installing..."

    case "$PM" in
        apt)
            sudo apt-get install -y ca-certificates gnupg lsb-release
            sudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
                | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo chmod a+r /etc/apt/keyrings/docker.gpg
            echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] \
                https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
                | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update -q
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            ;;
        dnf|yum)
            sudo "$PM" install -y yum-utils
            sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
            sudo "$PM" install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            sudo systemctl enable --now docker
            ;;
        pacman)
            sudo pacman -Sy --noconfirm docker docker-compose
            sudo systemctl enable --now docker
            ;;
        zypper)
            sudo zypper install -y docker docker-compose
            sudo systemctl enable --now docker
            ;;
        *)
            error "Cannot install Docker automatically on this distro."
            ;;
    esac
fi

info "Docker ready: $(docker --version)"

# Add the invoking user to the docker group so future sessions work without sudo.
# The remaining docker commands in this script still use sudo, so no re-login needed.
if [[ -n "${SUDO_USER:-}" ]] && ! groups "${SUDO_USER}" | grep -q docker; then
    sudo usermod -aG docker "${SUDO_USER}"
    info "User '${SUDO_USER}' added to docker group (takes effect on next login)."
fi

# Enable docker service if not already running
if ! sudo systemctl is-active --quiet docker; then
    sudo systemctl enable --now docker
fi


#############################################################
##### 10. Build and start containers
#############################################################

cd "$PROJECT_ROOT"

info "Pulling base images..."
sudo docker compose pull --quiet || true

info "Building and starting containers..."
sudo docker compose up -d --build

info "Waiting for health checks..."
retries=30
while [[ $retries -gt 0 ]]; do
    status=$(sudo docker compose ps --format json 2>/dev/null \
        | grep -o '"Health":"[^"]*"' | grep -v '"Health":""' | head -1 || echo "")
    [[ "${status}" == *"healthy"* ]] && break
    sleep 3; ((retries--))
done

echo ""
echo -e "${GREEN}══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Carniceria Artesanal — deployment complete!  ${NC}"
echo -e "${GREEN}══════════════════════════════════════════════${NC}"
echo ""
echo -e "  App:  http://$(hostname -I | awk '{print $1}'):3000"
echo -e "  Logs: sudo docker compose -C ${PROJECT_ROOT} logs -f"
echo ""
